### ISSUE TITLE
Hitting the escape key should have a consistent result

### ISSUE THREAD

**Issue by popthestack** [adamweeks/gifbar#100]
The escape key currently empties the search bar, clears the results, and closes the window, but only if there's text in the search bar and it has focus. If you delete the text in the search bar and then hit escape, the results are not cleared but the window is closed. If you hit escape when the search bar doesn't have focus it doesn't do anything.

Hitting escape should always do the following, regardless of focus:

 - Clear search bar if there's any text.
 - Clear search results, if any.
 - Close the window.

**Comment by adamweeks** [comment]
![hell yea](https://media2.giphy.com/media/l46Cm1fyR7Hy3DW4E/giphy.gif?fingerprint=e1bb72ff59a5ac50644b5644636c5e80)

**Comment by adamweeks** [comment]
I think we just need to add a document listener for keyup instead of `onKeyUp` on the input field.

**Comment by popthestack** [comment]
![yay](https://media2.giphy.com/media/10UeedrT5MIfPG/giphy.gif?fingerprint=e1bb72ff59a79b0f5035544e772db5e5)
