### ISSUE TITLE
Add keyboard shortcut that takes you straight to Gitbar search

### ISSUE THREAD

**Issue by mattm** [adamweeks/gifbar#15]
It would make searching more seamless.

**Comment by adamweeks** [comment]
Universal shortcut? So you can press like option-cmd-G and it will open the gifbar window?

**Comment by adamweeks** [comment]
This will probably need an "options" window.

**Comment by adamweeks** [comment]
https://github.com/electron/electron/blob/master/docs/api/global-shortcut.md
