### ISSUE TITLE
Bug: keyboard/text shortcuts don't work in search bar

### ISSUE THREAD

**Issue by joelmartinez** [adamweeks/gifbar#36]
for example, pressing `cmd+a` to select all ... or copy/pasting text

![](http://media3.giphy.com/media/3orif6zKPaNmW2SuKQ/giphy.gif) #gifbar

**Comment by adamweeks** [comment]
Works on development builds but not on production builds. Will investigate.

**Comment by joelmartinez** [comment]
![](http://media2.giphy.com/media/McjDXkZKw2v8A/giphy.gif)

**Comment by adamweeks** [comment]
This appears to be fixed on the latest version! @joelmartinez can you confirm?

**Comment by joelmartinez** [comment]
![](https://media1.giphy.com/media/3o7bu2s4p3ydnZ1WVy/giphy.gif)
