### ISSUE TITLE
Image alignment

### ISSUE THREAD

**Issue by adamweeks** [adamweeks/gifbar#4]
Images are left floated but leave tons of whitespace advice and below. Change to a different CSS method

http://www.w3schools.com/cssref/css3_pr_column-count.asp

**Comment by adamweeks** [comment]
Flexbox! http://codepen.io/cimmanon/pen/CcGlE

**Comment by popthestack** [comment]
Started this, but don't have a great solution yet. Am trying to find one that doesn't require including a full CSS library.

**Comment by adamweeks** [comment]
@popthestack feel free to use a full library if it makes things easier.
