### ISSUE TITLE
Optimizing the "focus" UX

### ISSUE THREAD

**Issue by joelmartinez** [adamweeks/gifbar#49]
As context, I'd like to present the experience of using spotlight as a reference. Generally speaking, when you press cmd+space on the mac, you can immediately start typing and seeing the results ... 

![image](https://cloud.githubusercontent.com/assets/90380/17405738/b0035162-5a2e-11e6-9384-4cb9344eae35.png)

If you press escape, it erases the original search term, and clears the search results; resetting you to the initial state

![image](https://cloud.githubusercontent.com/assets/90380/17405771/d7de4d18-5a2e-11e6-9c09-947f4c001e1a.png)

If however, you click away from the spotlight window to another application, then press cmd+space again, the same search term results will still be there, _except the search term is highlighted_

![image](https://cloud.githubusercontent.com/assets/90380/17405777/e3685ec6-5a2e-11e6-9390-066eab4c2e4e.png)

This lets you either resume hunting for whatever result you were looking for, or you can just start typing anew to search for something else; which again, essentially allows you to reset to the original state without any additional work.
## Problem

Currently, gifbar maintains state across all use cases ... so if I hide it after using it, and then bring it back, the original results are still there; but although the search box has focus and you can start typing, the term isn't highlighted, so it just appends text to the end (thus exacerbating the funky "cmd+a"/select all issues we've been seeing on some machines).

Additionally, when you click to navigate to another page of results, the results remain scrolled towards the bottom of the "page", so you have to manually scroll to the top.
## Proposal / Request
1. Esc to clear results and search term (if search box is empty, hide window)
2. When showing the screen, if there are old/existing results, scroll to the top and select the existing search term
3. Scroll to the top of the screen when navigating pages.

![Thank you](http://media3.giphy.com/media/FpaOqwlhaST0k/giphy.gif)

**Comment by adamweeks** [comment]
![bush](http://media3.giphy.com/media/o0rwAoBJ1VeRa/giphy.gif)

**Comment by popthestack** [comment]
+1

![yolo](http://media2.giphy.com/media/GuNCk0YU1BLi/giphy.gif)

**Comment by joelmartinez** [comment]
![](http://media1.giphy.com/media/9X5zV9eHAqAus/giphy.gif)
