### ISSUE TITLE
Option to "Open at Login"

### ISSUE THREAD

**Issue by joelmartinez** [adamweeks/gifbar#55]
Normally, you can right click on an app in the dock, and choose "Options > Open at Login". As `gifbar` has no dock icon, this is not possible by default. 

Ideally, there would be an option in the gifbar menu that would let you enable this. That way, it will automatically start when you reboot :)

![](http://media2.giphy.com/media/Tb2i75AlI926I/giphy.gif)

**Comment by popthestack** [comment]
+1 for menu option to open at login.

![yeah](http://media0.giphy.com/media/l6ZcdqQQCHBg4/giphy.gif)

**Comment by adamweeks** [comment]
https://www.npmjs.com/package/auto-launch
