### ISSUE TITLE
Clicking "copy" no longer hides window

### ISSUE THREAD

**Issue by adamweeks** [adamweeks/gifbar#58]
Might as well make it a user option to enable/disable as well

![fc](https://media1.giphy.com/media/10dshsB9Zs4Gn6/giphy.gif)

**Comment by adamweeks** [comment]
Fixed in cbf48ecfa4b0b87ada2e65fac1cf9ade6ca9792b

**Comment by popthestack** [comment]
![sweet](http://media1.giphy.com/media/zyin7TYoGmLAs/giphy.gif)
