### ISSUE TITLE
Save image urls to a local "collection"

### ISSUE THREAD

**Issue by adamweeks** [adamweeks/gifbar#7]
In order to reuse favorite images

**Comment by adamweeks** [comment]
![jars](http://media4.giphy.com/media/iMtRJu5qEdneE/giphy.gif)

**Comment by joelmartinez** [comment]
This could take the form of a star/favorite type of mechanism, maybe?

**Comment by adamweeks** [comment]
@joelmartinez yea, i like that idea, maybe a star in the top right. just need to figure out how to access those that we've starred

**Comment by adamweeks** [comment]
![img](https://media3.giphy.com/media/3o85xwxr06YNoFdSbm/giphy.gif)
