### ISSUE TITLE
Loading indicator

### ISSUE THREAD

**Issue by adamweeks** [adamweeks/gifbar#71]
After using gifbar on airplane wifi, it is VERY apparent that we need a loading indicator and loading state when searching.

![img](https://media3.giphy.com/media/3oEjI6SIIHBdRxXI40/giphy.gif?response_id=5963ef59ef419d0a76e88aa3)

**Comment by popthestack** [comment]
I think we had this in the angular version, but I never saw it. Just needed to fly on an airplane!

![wait](https://media2.giphy.com/media/iCbBAJpfvm17G/giphy.gif)
