### ISSUE TITLE
Paging doesn't reset on new search

### ISSUE THREAD

**Issue by adamweeks** [adamweeks/gifbar#89]
If you do a new search from page 2+ of the previous results, it will show page 2 of the newest search.

![img](https://media1.giphy.com/media/l41lVz0O2ESEQsSOI/giphy.gif?fingerprint=e1bb72ff5995b34d2f495430590368b0)

**Comment by popthestack** [comment]
![wat](https://media0.giphy.com/media/15iEv2lgdV5DO/giphy.gif?fingerprint=e1bb72ff5995b3b4324a6a65413593df)
